### PR TITLE
Follow user heading in free ride mode

### PR DESCRIPTION
**Pull request by jkgz**

### CODE REVIEW

**Comment by jkgz** [comment]
@mattrobmattrob I can't test heading on simulator, but I think this is all that is needed for map to follow postion + heading instead of just position when in free mode. If I should break .initial out into its own case, let me know.

**Review by mattrobmattrob — APPROVED** [review]
I don't like this. I think it should be like Apple Maps/Google Maps by default and toggleable to this state if desired but if this is Avi wants them LGTM.

**Comment by jkgz** [comment]
The support is there, I believe, now, in CustomRouteResponse if we want to throttle this back to just the 1st route returned. I think that's the only thing that would need to change to now show multiple possible routes.

I agree with you that showing multiple routes and letting user choose route on map is better. We can definitely get it there, if that's what you mean, but right now, I think it's worse to not show alternative route at all when the first one is sometimes really off, imo.

**Comment by mattrobmattrob** [comment]
> The support is there, I believe, now, in CustomRouteResponse if we want to throttle this back to just the 1st route returned. I think that's the only thing that would need to change to not show multiple possible routes.
> 
> 
> 
> I agree with you that showing multiple routes and letting user choose route on map is better. We can definitely get it there, if that's what you mean, but right now, I think it's worse to not show alternative route at all when the first one is sometimes really off, imo.

My guess is that this comment was for the other PR.

**Comment by jkgz** [comment]
> > The support is there, I believe, now, in CustomRouteResponse if we want to throttle this back to just the 1st route returned. I think that's the only thing that would need to change to not show multiple possible routes.
> > I agree with you that showing multiple routes and letting user choose route on map is better. We can definitely get it there, if that's what you mean, but right now, I think it's worse to not show alternative route at all when the first one is sometimes really off, imo.
> 
> My guess is that this comment was for the other PR.

Uh, yeah. My confusion, sorry. i thought you were saying you don't like showing 2 routes. Now I get it; you don't like it to follow heading in free mode. I tend to agree with you on that as well.

**Pull request merged**
